# Generated by Django 5.2 on 2026-06-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI — Contrat à Durée Indéterminée'), ('CDD', 'CDD — Contrat à Durée Déterminée'), ('STAGE', 'Convention de Stage'), ('FREELANCE', 'Contrat Freelance'), ('INTERIM', "Contrat d'Intérim")], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide pour un CDI', null=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=0, help_text='Salaire mensuel brut en FCFA', max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié'), ('EN_COURS', 'En cours de renouvellement')], default='ACTIF', max_length=20)),
                ('document', models.FileField(blank=True, help_text='Fichier PDF du contrat signé', null=True, upload_to='contrats/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to=settings.AUTH_USER_MODEL)),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departements.poste')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
    ]
