# Generated by Django 5.2 on 2026-06-26 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_contrat_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='categorie_pro',
            field=models.CharField(blank=True, choices=[('CAT_I_VI', 'Cat. I–VI (Ouvriers/Employés) — essai max 1 mois'), ('CAT_VII_X', 'Cat. VII–X (Agents de maîtrise) — essai max 3 mois'), ('CAT_XI_XII', 'Cat. XI–XII (Cadres) — essai max 6 mois')], default='CAT_VII_X', max_length=15),
        ),
        migrations.AddField(
            model_name='contrat',
            name='clause_non_concurrence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_debut_preavis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_fin_essai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='duree_non_concurrence_mois',
            field=models.IntegerField(default=12, help_text='Maximum légal : 12 mois (Art. 36)', validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='contrat',
            name='duree_preavis_jours',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='contrat',
            name='duree_totale_cdd_mois',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrat',
            name='essai_confirme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='essai_rompu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='horaires_travail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contrat',
            name='lieu_travail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contrat',
            name='periode_essai_mois',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrat',
            name='preavis_debute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrat',
            name='rayon_non_concurrence_km',
            field=models.IntegerField(default=50, help_text='Maximum légal : 50 km (Art. 36)', validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='contrat',
            name='renouvellement_numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contrat',
            name='visa_mintss',
            field=models.BooleanField(default=False, help_text='Visa MINTSS — obligatoire pour travailleurs étrangers'),
        ),
    ]
