# Generated by Django 5.2 on 2026-06-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, choices=[('BUREAUTIQUE', 'Bureautique & Productivité'), ('MARKETING', 'Marketing Digital'), ('DEV_WEB', 'Développement Web & App'), ('CYBERSEC', 'Cybersécurité'), ('GESTION_PROJET', 'Gestion de Projet'), ('INFRA_RESEAUX', 'Infrastructures & Réseaux'), ('IA', 'Intelligence Artificielle'), ('CLOUD', 'Cloud Computing'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
    ]
