# Generated by Django 5.2 on 2026-06-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_filiere_choices'),
        ('departements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='departements.departement'),
        ),
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='departements.poste'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYE', 'Employé'), ('MANAGER', 'Manager / Responsable'), ('RH', 'Responsable RH'), ('ADMIN', 'Administrateur Système')], default='EMPLOYE', max_length=20),
        ),
    ]
