# Generated by Django 5.2 on 2026-06-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='categorie_pro',
            field=models.CharField(blank=True, choices=[('I', 'Catégorie I'), ('II', 'Catégorie II'), ('III', 'Catégorie III'), ('IV', 'Catégorie IV'), ('V', 'Catégorie V'), ('VI', 'Catégorie VI'), ('VII', 'Catégorie VII'), ('VIII', 'Catégorie VIII'), ('IX', 'Catégorie IX'), ('X', 'Catégorie X'), ('XI', 'Catégorie XI'), ('XII', 'Catégorie XII')], max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='coefficient',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_urgence_tel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='date_dernier_avancement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='echelon',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='nationalite',
            field=models.CharField(blank=True, default='Camerounaise', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nb_enfants_a_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nb_enfants_moins_6_ans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='niu',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_cnps',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='personne_contact_urgence',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='prochain_avancement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve')], default='CELIBATAIRE', max_length=15),
        ),
    ]
