# Generated by Django 5.2 on 2026-06-26 08:43

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_adresse_user_categorie_pro_user_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil — Format JPG/PNG — Max 2 Mo — Ratio 3×4', null=True, upload_to=accounts.models.user_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
