# Generated by Django 5.2 on 2026-08-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_mobile',
            field=models.CharField(blank=True, help_text='Numero MTN MoMo ou Orange Money (ex: 655123456)', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='operateur_mobile',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], help_text='Operateur Mobile Money prefere', max_length=10),
        ),
    ]
