# Generated by Django 5.2 on 2026-06-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('slug', models.SlugField(help_text='Identifiant URL unique ex: acerfi-sarl', unique=True)),
                ('sigle', models.CharField(blank=True, help_text='Sigle ou acronyme ex: ACERFI', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                ('couleur_primaire', models.CharField(default='#1F3864', help_text='Couleur principale de la charte graphique', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#2E74B5', max_length=7)),
                ('secteur', models.CharField(choices=[('TECH', 'Technologie & Numérique'), ('SANTE', 'Santé & Pharmacie'), ('EDU', 'Éducation & Formation'), ('FIN', 'Finance & Assurance'), ('COM', 'Commerce & Distribution'), ('IND', 'Industrie & Production'), ('BTP', 'BTP & Immobilier'), ('AGR', 'Agriculture & Agroalimentaire'), ('SRV', 'Services aux entreprises'), ('ONG', 'ONG & Association'), ('AUTRE', 'Autre')], default='SRV', max_length=10)),
                ('taille', models.CharField(choices=[('TPE', 'TPE (1-9 employés)'), ('PME', 'PME (10-249 employés)'), ('ETI', 'ETI (250-4999 employés)'), ('GE', 'Grande entreprise (5000+)')], default='PME', max_length=10)),
                ('numero_contribuable', models.CharField(blank=True, max_length=50)),
                ('registre_commerce', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(default='Yaoundé', max_length=100)),
                ('pays', models.CharField(default='Cameroun', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('EXPIREE', 'Expirée'), ('ESSAI', "Période d'essai")], default='ESSAI', max_length=20)),
                ('date_debut_abonnement', models.DateField(blank=True, null=True)),
                ('date_fin_abonnement', models.DateField(blank=True, null=True)),
                ('nb_employes_max', models.IntegerField(default=50, help_text="Nombre max d'employés autorisés")),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('fuseau_horaire', models.CharField(default='Africa/Douala', max_length=50)),
                ('heure_debut_travail', models.TimeField(default='08:00')),
                ('heure_fin_travail', models.TimeField(default='17:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'ordering': ['nom'],
            },
        ),
    ]
