# Generated by Django 5.2 on 2026-06-09 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('INFO', 'Information'), ('SUCCES', 'Succès'), ('ALERTE', 'Alerte'), ('URGENT', 'Urgent')], default='INFO', max_length=10)),
                ('categorie', models.CharField(choices=[('CONGE', 'Congés & Absences'), ('EVALUATION', 'Évaluation & Objectifs'), ('CONTRAT', 'Contrats'), ('PAIE', 'Paie & Bulletins'), ('FORMATION', 'Formations'), ('RECRUTEMENT', 'Recrutements'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=15)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, help_text='URL relative vers la page concernée', max_length=300)),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
