# Generated by Django 5.2 on 2026-06-09 07:48

import django.core.validators
import django.db.models.deletion
import objectifs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_periode', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé'), ('ARCHIVE', 'Archivé')], default='EN_COURS', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Période d'évaluation",
                'verbose_name_plural': "Périodes d'évaluation",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('indicateur', models.CharField(blank=True, max_length=200)),
                ('cible', models.CharField(blank=True, max_length=100)),
                ('priorite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20)),
                ('statut', models.CharField(choices=[('NON_COMMENCE', 'Non commencé'), ('EN_COURS', 'En cours'), ('ATTEINT', 'Atteint'), ('DEPASSE', 'Dépassé'), ('NON_ATTEINT', 'Non atteint'), ('ABANDONNE', 'Abandonné')], default='NON_COMMENCE', max_length=20)),
                ('progression', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('commentaire_employe', models.TextField(blank=True)),
                ('commentaire_manager', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_assignes', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='objectifs.periodeevaluation')),
            ],
            options={
                'verbose_name': 'Objectif',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_competences', objectifs.models.NoteField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_objectifs', objectifs.models.NoteField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_comportement', objectifs.models.NoteField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_initiative', objectifs.models.NoteField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_travail_equipe', objectifs.models.NoteField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_communication', objectifs.models.NoteField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note_globale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('points_forts', models.TextField(blank=True)),
                ('axes_amelioration', models.TextField(blank=True)),
                ('objectifs_periode_suiv', models.TextField(blank=True)),
                ('commentaire_employe', models.TextField(blank=True)),
                ('commentaire_rh', models.TextField(blank=True)),
                ('analyse_ia', models.JSONField(blank=True, null=True)),
                ('score_ia', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('SIGNE', 'Signé'), ('CONTESTE', 'Contesté')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('evaluateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_faites', to=settings.AUTH_USER_MODEL)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='objectifs.periodeevaluation')),
            ],
            options={
                'verbose_name': 'Évaluation de performance',
                'verbose_name_plural': 'Évaluations de performance',
                'ordering': ['-created_at'],
                'unique_together': {('employe', 'periode')},
            },
        ),
    ]
