# Generated by Django 5.2 on 2026-05-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rapports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_engagement', models.IntegerField(default=0, help_text='Score 0–100')),
                ('points_forts', models.JSONField(default=list)),
                ('points_amelioration', models.JSONField(default=list)),
                ('recommandation', models.TextField(blank=True, help_text="Recommandation pour l'encadreur")),
                ('synthese', models.TextField(blank=True, help_text='Synthèse générale du rapport')),
                ('niveau_alerte', models.CharField(choices=[('AUCUNE', 'Aucune alerte'), ('FAIBLE', 'Alerte faible'), ('MOYENNE', 'Alerte moyenne'), ('ELEVEE', 'Alerte élevée')], default='AUCUNE', max_length=10)),
                ('motif_alerte', models.TextField(blank=True)),
                ('modele_utilise', models.CharField(blank=True, max_length=100)),
                ('tokens_utilises', models.IntegerField(default=0)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_ia', to='rapports.rapporthebdomadaire')),
            ],
            options={
                'verbose_name': 'Analyse IA',
                'verbose_name_plural': 'Analyses IA',
                'ordering': ['-date_analyse'],
            },
        ),
    ]
