# Generated by Django 5.2 on 2026-06-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseia',
            name='competences_detectees',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analyseia',
            name='progression_estimee',
            field=models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYENNE', 'Moyenne'), ('BONNE', 'Bonne'), ('EXCELLENTE', 'Excellente')], default='MOYENNE', max_length=15),
        ),
    ]
