# Generated by Django 5.2 on 2026-06-04 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#2E74B5', max_length=7)),
                ('icone', models.CharField(default='fas fa-building', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('niveau', models.CharField(choices=[('JUNIOR', 'Junior'), ('CONFIRME', 'Confirmé'), ('SENIOR', 'Senior'), ('CHEF', 'Chef / Responsable'), ('DIRECTION', 'Direction')], default='JUNIOR', max_length=20)),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=0, help_text='Salaire minimum en FCFA', max_digits=10, null=True)),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=0, help_text='Salaire maximum en FCFA', max_digits=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='departements.departement')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['departement', 'titre'],
            },
        ),
    ]
