# Generated by Django 5.2 on 2026-06-09 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportIAMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
                ('type_rapport', models.CharField(choices=[('GLOBAL', 'Global'), ('DEPARTEMENT', 'Par département'), ('EMPLOYE', 'Par employé')], default='GLOBAL', max_length=20)),
                ('donnees_collectees', models.JSONField(default=dict)),
                ('contenu_rapport', models.TextField(blank=True)),
                ('resume_executif', models.TextField(blank=True)),
                ('indicateurs_cles', models.JSONField(default=dict)),
                ('alertes_ia', models.JSONField(default=list)),
                ('recommandations', models.JSONField(default=list)),
                ('score_sante_rh', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('EN_GENERATION', 'En génération'), ('GENERE', 'Généré'), ('ERREUR', 'Erreur')], default='EN_GENERATION', max_length=20)),
                ('message_erreur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_ia', to='departements.departement')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_ia', to=settings.AUTH_USER_MODEL)),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_ia_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport IA mensuel',
                'verbose_name_plural': 'Rapports IA mensuels',
                'ordering': ['-annee', '-mois', '-created_at'],
                'unique_together': {('mois', 'annee', 'type_rapport', 'departement', 'employe')},
            },
        ),
    ]
