# Generated by Django 5.2 on 2026-06-09 12:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Configuration principale', max_length=100)),
                ('salaire_minimum', models.DecimalField(decimal_places=0, default=0, help_text='SMIG mensuel en FCFA', max_digits=12)),
                ('taux_cnps_employe', models.DecimalField(decimal_places=4, default=Decimal('0.028'), max_digits=6)),
                ('taux_cnps_employeur', models.DecimalField(decimal_places=4, default=Decimal('0.077'), max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration paie',
                'verbose_name_plural': 'Configurations paie',
            },
        ),
        migrations.CreateModel(
            name='ElementPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('GAIN', 'Gain / Prime'), ('RETENUE', 'Retenue')], max_length=10)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=0, help_text='Montant fixe en FCFA (exclusif avec taux)', max_digits=12, null=True)),
                ('taux', models.DecimalField(blank=True, decimal_places=4, help_text='Taux en fraction du salaire brut (ex : 0.05 = 5 %)', max_digits=6, null=True)),
                ('imposable', models.BooleanField(default=True, help_text="Inclus dans l'assiette IRPP")),
                ('is_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Élément de paie',
                'verbose_name_plural': 'Éléments de paie',
                'ordering': ['type', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
                ('salaire_brut', models.DecimalField(decimal_places=0, help_text='Salaire mensuel brut en FCFA', max_digits=12)),
                ('total_primes', models.DecimalField(decimal_places=0, default=0, help_text='Primes et indemnités diverses', max_digits=12)),
                ('cnps_employe', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('irpp', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('autres_retenues', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('salaire_net', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('PAYE', 'Payé')], default='BROUILLON', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_paie', to=settings.AUTH_USER_MODEL)),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_generes', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
