# Generated by Django 5.2 on 2026-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_bulletinpaie_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpaie',
            name='allocations_familiales',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='avances_salaire',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='avantages_nature',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cac',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='categorie_pro',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cfc_patronal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cfc_salarie',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cnps_patronal_at',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cnps_patronal_famille',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cnps_patronal_pension',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='cout_total_employeur',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='echelon',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='fne',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='gratification',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='indemnite_logement',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='indemnite_representation',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='indemnite_transport',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('cheque', 'Chèque')], default='virement', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='nb_heures_sup_25',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='nb_heures_sup_40',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='numero_cnps_employe',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='numero_cnps_employeur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='prime_anciennete',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='prime_assiduite',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='prime_rendement',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='prime_responsabilite',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='rav',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='revenu_net_categoriel',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='salaire_brut_cotisable',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='salaire_brut_imposable',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='salaire_categoriel',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='sursalaire',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='tdl',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='total_brut',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='total_retenues',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='salaire_brut',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total brut (calculé). Conservé pour compatibilité.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='total_primes',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Somme des primes imposables (calculé).', max_digits=12),
        ),
    ]
