# Generated by Django 5.2 on 2026-08-11 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('paie', '0003_bulletinpaie_allocations_familiales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirementMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], max_length=10)),
                ('numero_mobile', models.CharField(max_length=25)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('motif', models.CharField(default='Virement salarial', max_length=200)),
                ('reference_id', models.UUIDField(default=None, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('SUCCES', 'Succes'), ('ECHEC', 'Echec'), ('ANNULE', 'Annule')], default='EN_ATTENTE', max_length=15)),
                ('message_erreur', models.TextField(blank=True)),
                ('mode_demo', models.BooleanField(default=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulletin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virements', to='paie.bulletinpaie')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virements_mobiles', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virements_mobiles', to='entreprises.entreprise')),
                ('initie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virements_inities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Virement mobile',
                'verbose_name_plural': 'Virements mobiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
