# Generated by Django 5.2 on 2026-05-29 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_numero', models.PositiveIntegerField(help_text='Numéro de la semaine de stage (1, 2, 3...)')),
                ('date_debut_semaine', models.DateField()),
                ('date_fin_semaine', models.DateField()),
                ('activites_realisees', models.TextField(help_text='Décrivez les activités réalisées cette semaine')),
                ('projets_en_cours', models.TextField(blank=True, help_text="État d'avancement des projets")),
                ('difficultes', models.TextField(blank=True, help_text='Difficultés rencontrées')),
                ('objectifs_semaine_suiv', models.TextField(blank=True, help_text='Objectifs pour la semaine prochaine')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20)),
                ('commentaire_encadreur', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stagiaire', models.ForeignKey(limit_choices_to={'role': 'STAGIAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport hebdomadaire',
                'verbose_name_plural': 'Rapports hebdomadaires',
                'ordering': ['-date_debut_semaine'],
                'unique_together': {('stagiaire', 'semaine_numero')},
            },
        ),
    ]
