# Generated by Django 5.2 on 2026-06-08 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_arrivee_standard', models.TimeField(default='08:00')),
                ('heure_depart_standard', models.TimeField(default='17:00')),
                ('tolerance_retard_minutes', models.IntegerField(default=15, help_text='Minutes de tolérance avant de marquer un retard')),
                ('heures_journee_standard', models.DecimalField(decimal_places=2, default=8, max_digits=4)),
            ],
            options={
                'verbose_name': 'Configuration présences',
                'verbose_name_plural': 'Configurations présences',
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('CONGE', 'En congé'), ('FERIE', 'Jour férié'), ('WEEKEND', 'Week-end')], default='PRESENT', max_length=20)),
                ('heures_travaillees', models.DecimalField(blank=True, decimal_places=2, help_text='Heures travaillées dans la journée', max_digits=4, null=True)),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, help_text='Heures au-delà de 8h', max_digits=4)),
                ('note', models.TextField(blank=True, help_text='Observation ou justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
