# Generated by Django 5.2 on 2026-06-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('presences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='entreprises.entreprise'),
        ),
    ]
