# Generated by Django 5.2 on 2026-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0002_pointage_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='est_dimanche',
            field=models.BooleanField(default=False, help_text='True si la date est un dimanche'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='est_jour_ferie',
            field=models.BooleanField(default=False, help_text='True si la date est un jour férié officiel camerounais'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='est_nuit',
            field=models.BooleanField(default=False, help_text="True si l'heure d'arrivée ou de départ est entre 22h et 6h"),
        ),
        migrations.AddField(
            model_name='pointage',
            name='hs_dimanche',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Travail un dimanche (+40%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pointage',
            name='hs_ferie',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Travail un jour férié officiel (+100%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pointage',
            name='hs_jour_20',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HS de jour — 8 premières heures sup/semaine (+20%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pointage',
            name='hs_jour_30',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HS de jour — au-delà de 8h sup/semaine (+30%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pointage',
            name='hs_nuit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HS de nuit 22h–6h (+50%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='pointage',
            name='montant_hs_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total des majorations HS (FCFA)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heures_supplementaires',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HS brutes approximatives (>8h/jour). Utiliser les champs catégoriels.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='heures_travaillees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Heures travaillées dans la journée', max_digits=5, null=True),
        ),
    ]
