# Generated by Django 5.2 on 2026-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0003_pointage_est_dimanche_pointage_est_jour_ferie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='est_retard',
            field=models.BooleanField(default=False, help_text="True si l'arrivée dépasse 8h05 (tolérance 5 min)"),
        ),
        migrations.AddField(
            model_name='pointage',
            name='minutes_retard',
            field=models.IntegerField(default=0, help_text='Minutes de retard par rapport à 8h00'),
        ),
    ]
