# Generated by Django 5.2 on 2026-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0004_pointage_est_retard_pointage_minutes_retard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='hs_jour_40',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HS de jour — heures sup 17 à 20 de la semaine (+40%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='hs_ferie',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Travail un jour férié officiel (taux conventionnel, non fixé par le décret)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='hs_jour_30',
            field=models.DecimalField(decimal_places=2, default=0, help_text='HS de jour — heures sup 9 à 16 de la semaine (+30%)', max_digits=5),
        ),
    ]
