# Generated by Django 5.2 on 2026-06-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('jours_par_an', models.IntegerField(default=30, help_text='Nombre de jours alloués par an')),
                ('est_paye', models.BooleanField(default=True)),
                ('necessite_justificatif', models.BooleanField(default=False)),
                ('couleur', models.CharField(default='#2E74B5', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nb_jours', models.IntegerField(help_text='Calculé automatiquement')),
                ('motif', models.TextField(help_text='Raison de la demande')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='conges/justificatifs/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('commentaire_valideur', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to=settings.AUTH_USER_MODEL)),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides', to=settings.AUTH_USER_MODEL)),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='conges.typeconge')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(help_text='Année concernée ex: 2026')),
                ('jours_acquis', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('jours_pris', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('jours_en_attente', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to=settings.AUTH_USER_MODEL)),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes', to='conges.typeconge')),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congé',
                'unique_together': {('employe', 'type_conge', 'annee')},
            },
        ),
    ]
