# Generated by Django 5.2 on 2026-06-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_demandeconge_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='allocation_conge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='date_retour_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='jours_ouvrable_pauses',
            field=models.IntegerField(default=0, help_text='Jours fériés tombant en semaine pendant le congé'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='majoration_anciennete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='majoration_enfants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='notifie_valideur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeconge',
            name='code_legal',
            field=models.CharField(choices=[('ANNUEL', 'Congé annuel ordinaire'), ('MATERNITE', 'Congé de maternité'), ('MALADIE', 'Congé maladie'), ('PERMISSION', "Permission exceptionnelle d'absence"), ('SYNDICAL', 'Congé syndical'), ('SANS_SOLDE', 'Congé sans solde'), ('PATERNITE', 'Congé de paternité')], default='ANNUEL', max_length=30),
        ),
        migrations.AddField(
            model_name='typeconge',
            name='deductible_conge_annuel',
            field=models.BooleanField(default=True, help_text='Ce type de congé se déduit-il du solde de congé annuel ?'),
        ),
    ]
