# Generated by Django 5.2 on 2026-06-09 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='fas fa-graduation-cap', max_length=50)),
                ('couleur', models.CharField(default='#7B2D8B', max_length=7)),
            ],
            options={
                'verbose_name': 'Catégorie de formation',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('objectifs_pedagogiques', models.TextField(blank=True)),
                ('modalite', models.CharField(choices=[('PRESENTIEL', 'Présentiel'), ('DISTANCIEL', 'À distance'), ('HYBRIDE', 'Hybride'), ('ELEARNING', 'E-learning')], default='PRESENTIEL', max_length=20)),
                ('niveau', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé'), ('EXPERT', 'Expert')], default='INTERMEDIAIRE', max_length=20)),
                ('duree_heures', models.IntegerField(default=8)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('formateur', models.CharField(blank=True, max_length=200)),
                ('cout', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('places_max', models.IntegerField(default=20)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.categorieformation')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CompetenceAcquise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=200)),
                ('niveau_acquis', models.CharField(choices=[('NOTIONS', 'Notions'), ('PRATIQUE', 'Pratique'), ('MAITRISE', 'Maîtrise'), ('EXPERTISE', 'Expertise')], default='PRATIQUE', max_length=20)),
                ('date_acquisition', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_acquises', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Compétence acquise',
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('INSCRIT', 'Inscrit'), ('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('note_formation', models.IntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('certificat', models.FileField(blank=True, null=True, upload_to='formations/certificats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formations', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.formation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription à une formation',
                'unique_together': {('employe', 'formation')},
            },
        ),
    ]
