# Generated by Django 5.2 on 2026-06-08 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='fas fa-file', max_length=50)),
                ('couleur', models.CharField(default='#2E74B5', max_length=7)),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='documents_rh/%Y/%m/')),
                ('taille_fichier', models.IntegerField(default=0, help_text='Taille en octets')),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('visibilite', models.CharField(choices=[('PRIVE', 'Privé (RH uniquement)'), ('EMPLOYE', "Visible par l'employé"), ('EQUIPE', "Visible par l'équipe"), ('TOUS', 'Visible par tous')], default='EMPLOYE', max_length=20)),
                ('date_expiration', models.DateField(blank=True, help_text="Date d'expiration du document (si applicable)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.categoriedocument')),
                ('employe', models.ForeignKey(blank=True, help_text="Laisser vide pour document d'entreprise général", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_rh', to=settings.AUTH_USER_MODEL)),
                ('uploade_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document RH',
                'verbose_name_plural': 'Documents RH',
                'ordering': ['-created_at'],
            },
        ),
    ]
