# Generated by Django 5.2 on 2026-06-09 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('AVERT_ORAL', 'Avertissement oral'), ('AVERT_ECRIT', 'Avertissement écrit'), ('BLAME', 'Blâme'), ('MISE_GARDE', 'Mise en garde'), ('MISE_PIED', 'Mise à pied'), ('RETROGRADATION', 'Rétrogradation'), ('LICENCIEMENT', 'Licenciement')], max_length=20)),
                ('motif', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('date_faits', models.DateField()),
                ('date_sanction', models.DateField()),
                ('date_debut_effet', models.DateField(blank=True, null=True)),
                ('date_fin_effet', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('NOTIFIEE', "Notifiée à l'employé"), ('ACCEPTEE', "Acceptée par l'employé"), ('CONTESTEE', 'Contestée'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='sanctions/')),
                ('reponse_employe', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('mesures_correctives', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
                ('prononcee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_prononcees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sanction disciplinaire',
                'ordering': ['-date_sanction'],
            },
        ),
    ]
