# Generated by Django 5.2 on 2026-06-26 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanctions', '0002_sanction_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='conteste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanction',
            name='date_debut_mise_a_pied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanction',
            name='date_fin_mise_a_pied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanction',
            name='date_notification_it',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sanction',
            name='delai_48h_respecte',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='sanction',
            name='delai_reponse_jours',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='sanction',
            name='duree_mise_a_pied_jours',
            field=models.IntegerField(blank=True, help_text='Durée maximale légale : 8 jours ouvrables (Art. 30 al.3)', null=True, validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='sanction',
            name='issue_contestation',
            field=models.CharField(blank=True, choices=[('EN_COURS', "En cours d'instruction"), ('MAINTENUE', 'Sanction maintenue'), ('ANNULEE', 'Sanction annulée'), ('INDEMNITE_VERSEE', 'Indemnité compensatrice versée')], max_length=20),
        ),
        migrations.AddField(
            model_name='sanction',
            name='montant_retenue_salaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sanction',
            name='notifie_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sanction',
            name='retenue_appliquee_paie',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='type_sanction',
            field=models.CharField(choices=[('AVERTISSEMENT', 'Avertissement écrit'), ('BLAME', 'Blâme'), ('MISE_A_PIED', 'Mise à pied'), ('LICENCIEMENT_FAUTE_GRAVE', 'Licenciement pour faute grave'), ('LICENCIEMENT_FAUTE_LOURDE', 'Licenciement pour faute lourde')], max_length=30),
        ),
    ]
