# Generated by Django 5.2 on 2026-05-29 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetSoutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PROPOSE', 'Proposé'), ('VALIDE', 'Validé'), ('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('SOUTENU', 'Soutenu')], default='PROPOSE', max_length=20)),
                ('livrable', models.FileField(blank=True, null=True, upload_to='livrables/')),
                ('date_soutenance', models.DateField(blank=True, null=True)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('commentaire_jury', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stagiaire', models.OneToOneField(limit_choices_to={'role': 'STAGIAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='projet_soutenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet de soutenance',
                'verbose_name_plural': 'Projets de soutenance',
            },
        ),
        migrations.CreateModel(
            name='StagePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ABANDONNE', 'Abandonné')], default='EN_COURS', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Objectifs ou contexte du stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encadreur', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENCADREUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_encadres', to=settings.AUTH_USER_MODEL)),
                ('stagiaire', models.ForeignKey(limit_choices_to={'role': 'STAGIAIRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='periodes_stage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Période de stage',
                'verbose_name_plural': 'Périodes de stage',
                'ordering': ['-date_debut'],
            },
        ),
    ]
