# Generated by Django 5.2 on 2026-10-08 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetsoutenance',
            name='stagiaire',
            field=models.OneToOneField(limit_choices_to={'role': 'EMPLOYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='projet_soutenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stageperiode',
            name='encadreur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_encadres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stageperiode',
            name='stagiaire',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYE'}, on_delete=django.db.models.deletion.CASCADE, related_name='periodes_stage', to=settings.AUTH_USER_MODEL),
        ),
    ]
