# Generated by Django 5.2 on 2026-06-09 08:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('cv', models.FileField(upload_to='recrutements/cv/')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='recrutements/lettres/')),
                ('linkedin', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('RECUE', 'Reçue'), ('EN_COURS', "En cours d'examen"), ('ENTRETIEN_RH', 'Entretien RH'), ('ENTRETIEN_TECH', 'Entretien technique'), ('OFFRE_FAITE', 'Offre faite'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ABANDONNEE', 'Abandonnée')], default='RECUE', max_length=20)),
                ('note_interne', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire_rh', models.TextField(blank=True)),
                ('analyse_cv_ia', models.TextField(blank=True)),
                ('score_cv_ia', models.IntegerField(blank=True, null=True)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidature',
                'ordering': ['-date_candidature'],
            },
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(choices=[('RH', 'Entretien RH'), ('TECHNIQUE', 'Entretien technique'), ('DIRECTION', 'Entretien direction'), ('TELEPHONIQUE', 'Entretien téléphonique')], max_length=20)),
                ('date_heure', models.DateTimeField()),
                ('duree_minutes', models.IntegerField(default=60)),
                ('lieu', models.CharField(default="Bureaux de l'entreprise", max_length=200)),
                ('resultat', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('POSITIF', 'Positif'), ('NEGATIF', 'Négatif'), ('A_REVOIR', 'À revoir')], default='EN_ATTENTE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='recrutements.candidature')),
                ('intervieweur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_menes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entretien',
                'ordering': ['date_heure'],
            },
        ),
        migrations.CreateModel(
            name='OffreEmploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('FREELANCE', 'Freelance')], default='CDI', max_length=20)),
                ('niveau_experience', models.CharField(choices=[('DEBUTANT', 'Débutant (0-2 ans)'), ('JUNIOR', 'Junior (2-5 ans)'), ('CONFIRME', 'Confirmé (5-10 ans)'), ('SENIOR', 'Senior (10+ ans)')], default='JUNIOR', max_length=20)),
                ('description', models.TextField()),
                ('competences_requises', models.TextField(help_text='Liste des compétences requises')),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('lieu', models.CharField(default='Yaoundé, Cameroun', max_length=200)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('nb_postes', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('EN_PAUSE', 'En pause'), ('CLOTUREE', 'Clôturée'), ('POURVUE', 'Poste pourvu')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_creees', to=settings.AUTH_USER_MODEL)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='departements.departement')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='departements.poste')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidature',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrutements.offreemploi'),
        ),
        migrations.AlterUniqueTogether(
            name='candidature',
            unique_together={('offre', 'email')},
        ),
    ]
