# Generated by Django 5.2 on 2026-06-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutements', '0002_offreemploi_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='aptitude_medicale',
            field=models.CharField(choices=[('APTE', 'Apte'), ('APTE_RESERVES', 'Apte avec réserves'), ('INAPTE', 'Inapte'), ('EN_ATTENTE', 'Visite non encore effectuée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='candidature',
            name='cnps_declare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_declaration_cnps',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_embauche_effective',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_embauche_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_visite_medicale',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='delai_cnps_respecte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidature',
            name='est_etranger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidature',
            name='inscrit_registre_personnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidature',
            name='numero_cnps_attribue',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidature',
            name='numero_registre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidature',
            name='visa_mintss_obtenu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidature',
            name='visite_medicale_faite',
            field=models.BooleanField(default=False),
        ),
    ]
