# Generated by Django 5.2 on 2026-06-09 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementCarriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('EMBAUCHE', 'Embauche'), ('PROMOTION', 'Promotion'), ('MUTATION', 'Mutation département'), ('CHANGEMENT_POSTE', 'Changement de poste'), ('AUGMENTATION', 'Augmentation salariale'), ('FORMATION', 'Formation suivie'), ('CONGE_LONG', 'Congé longue durée'), ('AVERTISSEMENT', 'Avertissement'), ('FELICITATION', 'Félicitation / Award'), ('DEPART', 'Départ'), ('AUTRE', 'Autre événement')], max_length=30)),
                ('date_evenement', models.DateField()),
                ('titre', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('salaire_avant', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('salaire_apres', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='carriere/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departement_apres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivees_carriere', to='departements.departement')),
                ('departement_avant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departs_carriere', to='departements.departement')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_carriere', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('poste_apres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivees_carriere', to='departements.poste')),
                ('poste_avant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departs_carriere', to='departements.poste')),
            ],
            options={
                'verbose_name': 'Événement de carrière',
                'verbose_name_plural': 'Événements de carrière',
                'ordering': ['-date_evenement'],
            },
        ),
    ]
